### ISSUE TITLE
加入 eslint

### ISSUE THREAD

**Issue by lixiang810** [Icalingua/Icalingua-React#1]
既然重构，就没理由不用 eslint 了，尤其 react 有相当成熟的 eslint 方案。
https://github.com/toshi-toma/eslint-config-airbnb-typescript-prettier
之后再写一下 .prettierrc.js 以配置码风。

**Comment by rain15z3** [comment]
收到，我对这个不太熟悉，你可以来呢qwq

**Comment by lixiang810** [comment]
懂了，直接安排好

**Comment by lixiang810** [comment]
然而alloy也报了一大堆错误（
